package com.mailgun.model.templates;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;

/**
 * <p>
 * Template request.
 * </p>
 *
 * @see <a href="https://documentation.mailgun.com/en/latest/api-templates.html">Templates</a>
 */
@Getter
@ToString
@EqualsAndHashCode
@Builder
public class TemplateRequest {

    /**
     * <p>
     * Name of the template being created.
     * </p>
     * <p>
     * The name can contain alpha characters, digits and next symbols: <code>.-_~</code>
     * </p>
     */
    String name;

    /**
     * <p>
     * Description of the template being created.
     * </p>
     */
    String description;

    /**
     * <p>
     * (Optional) Content of the template.
     * </p>
     */
    String template;

    /**
     * <p>
     * (Optional) Initial tag of the created version. If template parameter is provided and tag is missing default value initial is used.
     * </p>
     * <p>
     * The tag can contain alpha characters, digits and next symbols: <code>.-_~</code>
     * </p>
     */
    String tag;

    /**
     * <p>
     * (Optional) The template engine to use to render the template.
     * Valid only if template parameter is provided.
     * </p>
     * <p>
     * Currently the API supports only one engine: <code>handlebars</code>.
     * </p>
     */
    String engine;

    /**
     * <p>
     * (Optional) Version comment.
     * Valid only if new version is being created (template parameter is provided);
     * </p>
     */
    String comment;

    /**
     * <p>
     * (Optional) Key value JSON object of headers to be stored with the template.
     * Where key is the header name and value is the header value.
     * The header names <code>From</code>, <code>Subject</code>, and <code>Reply-To</code> are the only ones currently supported.
     * These headers will be inserted into the MIME at the time we attempt delivery.
     * </p>
     * <p>
     * Headers set at the message level will override headers set on the template.
     * e.g. Setting the From header at the time of sending will override the From header saved on the template.
     * Additionally, headers generated by templates are not reflected on the accepted event as they are not prepended to the message until the message is prepped for delivery.
     * If a From header is not provided either in the message or template, we will default to <code>postmaster@your-sending-domain.tld</code>
     * </p>
     */
    String headers;

    /**
     * <p>
     * (Optional) Optional metadata field api user can indicate who created the template.
     * </p>
     */
    String createdBy;

}
