package com.mailgun.model.templates;

import com.mailgun.enums.YesNo;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;

/**
 * <p>
 * Request to update template version.
 * </p>
 *
 * @see <a href="https://documentation.mailgun.com/en/latest/api-templates.html">Templates</a>
 */
@Getter
@ToString
@EqualsAndHashCode
@Builder
public class UpdateTemplateVersionRequest {

    /**
     * <p>
     * (Optional) The new content of the version.
     * </p>
     */
    String template;

    /**
     * <p>
     * (Optional) New comment for the provided version.
     * </p>
     */
    String comment;

    /**
     * <p>
     * (Optional) If this flag is set to <code>YES</code>, this version becomes active.
     * </p>
     */
    String active;

    /**
     * <p>
     * (Optional) Key value JSON object of headers to be stored with the template version.
     * Where key is the header name and value is the header value.
     * The header names <code>From</code>, <code>Subject</code>, and <code>Reply-To</code> are the only ones currently supported.
     * These headers will be inserted into the MIME at the time we attempt delivery.
     * </p>
     * <p>
     * Headers set at the message level will override headers set on the template.
     * e.g. Setting the From header at the time of sending will override the From header saved on the template.
     * Additionally, headers generated by templates are not reflected on the accepted event as they are not prepended to the message until the message is prepped for delivery.
     * If a From header is not provided either in the message or template, we will default to <code>postmaster@your-sending-domain.tld</code>
     * </p>
     */
    String headers;

    public static class UpdateTemplateVersionRequestBuilder {

        /**
         * <p>
         * (Optional) If this flag is set to <code>TRUE</code>, this version becomes active.
         * <p>
         *
         * @param active flag whether the version is active
         * @return Returns a reference to this object so that method calls can be chained together.
         */
        public UpdateTemplateVersionRequest.UpdateTemplateVersionRequestBuilder active(boolean active) {
            if (active) {
                this.active = YesNo.YES.getValue();
            }
            return this;
        }
    }

}
